### ISSUE TITLE
Todo tracker 

### ISSUE THREAD

**Issue by anihm136** [anihm136/moonfly-statusline-themes#1]
This issue is for tracking basic setup of the repo before making it available on PESOS

- [ ] Fix themes (only spacegray is working as of now)
- [ ] Add readme
- [ ] Add contributing guidelines
- [ ] Add screenshots of themes
- [ ] Add basic documentation
